### ISSUE TITLE
Does not work with Angular-CLI Final

### ISSUE THREAD

**Issue by jculverwell** [Gbuomprisco/ng2-tag-input#59]
Thank you for an excellent project.

Unfortunately, it looks like it isn't working with Angular-CLI final.  I have created a repo here where you can see the issue https://github.com/jculverwell/NgTagsInputWithAngularCLIFinal

Looks like a problem with Zone.js.  Not sure if you adjust your project to avoid this issue or if it is a zone.js issue.  I will raise with the zone.js repo as well.

```
zone.js:129 Uncaught TypeError: Cannot read property 'name' of undefined
exports.functionName    @   function-name.ts?6954:7
(anonymous function)    @   transformer.ts?d0de:89
dependencies    @   transformer.ts?d0de:89
(anonymous function)    @   transformer.ts?d0de:145
load    @   transformer.ts?d0de:53
exports.transform   @   transformer.ts?d0de:61
(anonymous function)    @   transformer.ts?d0de:161
transformChildren   @   transformer.ts?d0de:159
(anonymous function)    @   transformer.ts?d0de:180
load    @   transformer.ts?d0de:53
exports.transform   @   transformer.ts?d0de:61
(anonymous function)    @   transformer.ts?d0de:161
transformChildren   @   transformer.ts?d0de:159
(anonymous function)    @   transformer.ts?d0de:180
load    @   transformer.ts?d0de:53
exports.transform   @   transformer.ts?d0de:61
(anonymous function)    @   transformer.ts?d0de:161
transformChildren   @   transformer.ts?d0de:159
(anonymous function)    @   transformer.ts?d0de:180
load    @   transformer.ts?d0de:53
exports.transform   @   transformer.ts?d0de:61
exports.transformToTree @   mutable-tree-factory.ts?f7a1:12
(anonymous function)    @   mutable-tree-factory.ts?f7a1:40
exports.createTreeFromElements  @   mutable-tree-factory.ts?f7a1:40
updateTree  @   backend.ts:65
update  @   backend.ts:90
(anonymous function)    @   backend.ts:101
SafeSubscriber.__tryOrUnsub @   Subscriber.js?215e:223
SafeSubscriber.next @   Subscriber.js?215e:172
Subscriber._next    @   Subscriber.js?215e:125
Subscriber.next @   Subscriber.js?215e:89
DebounceTimeSubscriber.debouncedNext    @   debounceTime.js?500c:98
dispatchNext    @   debounceTime.js?500c:114
AsyncAction._execute    @   AsyncAction.js?e414:111
AsyncAction.execute @   AsyncAction.js?e414:86
AsyncScheduler.flush    @   AsyncScheduler.js?ae69:36
ZoneDelegate.invokeTask @   zone.js:225
Zone.runTask    @   zone.js:125
ZoneTask.invoke @   zone.js:293
```

**Comment by Gbuomprisco** [comment]
I'll have a look :)

**Comment by jculverwell** [comment]
Thank you

**Comment by Gbuomprisco** [comment]
Hi @jculverwell, can you try with the new version I released? I tried your repo and all was working fine. I only had to also install `typings`. Let me know :)

**Comment by jculverwell** [comment]
Hmm, still didn't work.  Same error.  I'm guessing either something is screwed on my machine or maybe its platform specific  Are you using windows or Mac?  I'm on WIndows 10.  Thanks

**Comment by Gbuomprisco** [comment]
I tried on Linux. Will try today on a Mac :)

**Comment by jculverwell** [comment]
I completely removed nodejs and tried again today and was still getting the same issue.  I then took a brand new machine, installed windows 10, and nodejs and then angular-cli and this also has the same issue.  Unless I have something really weird going on (or I'm being rally stupid :)) I think I can safely say that this project does not work with angular-cli on Windows 10.  I would love to help resolve this.  I have a windows machine I would be more than happy to let you remote into if you would like to see the problem first hand.

**Comment by cbjartli** [comment]
I have the same issue, and same setup as jculverwell.

**Comment by Gbuomprisco** [comment]
@cbjartli @jculverwell Thanks for looking into this. I think it might be related to the component used for the dropdown if it only happens if autocomplete is set to true. I'll have a further look asap :)

**Comment by jculverwell** [comment]
Thank you, if you need a Windows machine to test on I could let you remote into one of mine.

**Comment by andrew-willens** [comment]
I'm experiencing the same problem - if autocomplete is set to true, the browser console logs a "can't read 'name' from undefined" error. I'm on OSX El Capitan, so I don't believe it's a Windows issue.
![screen shot 2016-12-12 at 5 36 47 pm](https://cloud.githubusercontent.com/assets/6180388/21119684/b8a95cc0-c091-11e6-996c-d7cae00426ae.png)

**Comment by Gbuomprisco** [comment]
Sorry guys, I've never seen this error, and not sure how to reproduce it. :| I'm closing this issue for now - would be great if someone could dig deeper and submit a PR?
